### ISSUE TITLE
Assimilation of single session into multi-coach session

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#9] opened 2020-10-23 13:23 UTC
Its took some timing for Joe and me to agree to Sunday's two sessions and which one of us was going to post a multi-session etc.  There may also be times when one only posts one session (no one else interested) but as the queue for reserve places builds up someone does offer a session.  So being able to click a button on a single session to "multi-coach session"-arize it would be useful.

**Comment by bonejon** [comment] 2021-05-02 18:50
Duplicate of #15 Closing.

**Closed as completed by bonejon** 2021-05-02 18:50 UTC
Labels: duplicate
